<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Redirecting;

/**
 * RedirectingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedirectingRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Check for uniqueness short url value
     * @param string $url
     * @return boolean
     */
    public function isUniqueShortUrl($url)
    {
        $matches = $this->getEntityManager()
                        ->getRepository('AppBundle:Redirecting')
                        ->findOneByShortUrl($url);

        return !$matches;
    }

    /**
     * Save urls pair for redirecting
     * @param string $longUrl
     * @param string $shortUrl
     */
    public function saveUrlPair($longUrl, $shortUrl){
        $redirecting = new Redirecting();
        $redirecting->setLongUrl($longUrl);
        $redirecting->setShortUrl($shortUrl);

        $em = $this->getEntityManager();
        $em->persist($redirecting);
        $em->flush();
    }

    /**
     * Increment usage counter of url redirecting
     * @param Redirecting $redirecting
     */
    public function incUsageCount(Redirecting $redirecting){
        $redirecting->setUsageCount($redirecting->getUsageCount() + 1);
        $em = $this->getEntityManager();
        $em->persist($redirecting);
        $em->flush();
    }
}
