<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Redirecting;
use AppBundle\Service\ResponseBuilder;
use Doctrine\ORM\Mapping;

/**
 * RedirectingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedirectingRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Check for uniqueness short url value
     * @param string $url
     * @return boolean
     */
    public function isUniqueShortUrl($url)
    {
        $matches = $this->getEntityManager()
            ->getRepository('AppBundle:Redirecting')
            ->findOneByShortUrl($url);

        return !$matches;
    }

    /**
     * Save redirecting entity
     * @param Redirecting $redirecting
     */
    public function save($redirecting)
    {
        $em = $this->getEntityManager();
        $em->persist($redirecting);
        $em->flush();
    }

    /**
     * Increment usage counter of url redirecting
     * @param Redirecting $redirecting
     */
    public function incUsageCount(Redirecting $redirecting)
    {
        $redirecting->setUsageCount($redirecting->getUsageCount() + 1);
        $em = $this->getEntityManager();
        $em->persist($redirecting);
        $em->flush();
    }

}
