# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
services:
    redirecting_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Redirecting

    app.url_shortener:
        class:        AppBundle\Service\UrlShortener
        arguments:
          - @redirecting_repository